name: Run script tests
on:
    push:
    pull_request:
    release:

jobs:
    tests_scripts:
        name: Test Scripts Functionally
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository to the runner
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Kitty
              # So we can see the output
              run: |
                  curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

            - name: Download run data
              # 2 - BUSCO full table
              # 3 - A lepidoptera genome .fai file
              run: |

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Run Python Script
              # --reference is the full busco table
              # --query is the full busco table
              run: |
                  python3 /src/buscopainter.py --reference_table ./test_data/busco_full_table.tsv --query_table reference_data/Merian_elements_full_table.tsv

            - name: Print output files
              run: ls -lh *

            - name: setup R
              uses: r-lib/actions/setup-r@v2
              with:
                  use-public-rspm: true

            - name: Install R dependencies
              uses: r-lib/actions/setup-r-dependencies@v2
              with:
                  extra-packages:: any::tidyverse, any::scales, any::optparse

            - name: Run R Script
              # --file is the '*buscopainter_complete_location.tsv' file
              # --index is the genome's faidx file
              run: source("src/plot_buscopainter.R")
              shell: Rscript {0} --file ./test_data/buscopainter_buscopainter_complete_location.tsv --prefix "github_plot" --index ""

            - name: Print output files
              run: ls -lh *
