name: Linting
on:
  pull_request:
  release:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ruff-action-install
      - uses: astral-sh/ruff-action@v3.5.0
      - run: ruff check --fix
      - run: ruff format
