name: Linting
on:
  push:
  pull_request:
  release:

jobs:
  RLinting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      - name: Lint
        run: lintr::lint(filename="./src/plot_buscopainter.R")
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true

  PythonLinting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
  
      - name: ruff-check-python
        # You may pin to the exact commit or the version.
        # uses: astral-sh/ruff-action@0c50076f12c38c3d0115b7b519b54a91cb9cf0ad
        uses: astral-sh/ruff-action@v3.5.0
        with:
          src: "./src"
          args: check

      - name: ruff-format-python
        # You may pin to the exact commit or the version.
        # uses: astral-sh/ruff-action@0c50076f12c38c3d0115b7b519b54a91cb9cf0ad
        uses: astral-sh/ruff-action@v3.5.0
        with:
          src: "./src"
          args: format --diff
