name: Linting
on:
  pull_request:
  release:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install the latest version of ruff
      uses: astral-sh/ruff-action@v3
      with:
        version: "latest"
        
